site_name: ac-library-mojo
site_url: https://shogo314.github.io/ac-library-mojo-test/
repo_url: https://github.com/shogo314/ac-library-mojo-test
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.action.edit
    - versioning

plugins:
  - search
  - mike

nav:
  - Home: index.md
  - API: api.md

extra:
  version:
    provider: mike
